### ISSUE TITLE
EmailController extends AbstractActionController

### ISSUE THREAD

**Issue by man4red** [aqilix/zf3-apigilty-oauth2#3]
is it correct?
```php
...
use Zend\Mvc\Controller\AbstractActionController;
...
class EmailController extends AbstractActionController
...
```

to 

```php
use Zend\Mvc\Console\Controller\AbstractConsoleController;
...
class EmailController extends AbstractConsoleController
...
```

**Comment by dollyaswin** [comment]
Hi @man4red,

Thanks for watching this project. I think that is the problem. I have also check my production code, and it use `Zend\Mvc\Console\Controller\AbstractConsoleController`. I think I forgot to push it to this repository. Please create pull request for this bug, I will approve it. By this way, your name will be exist in commit history.

Regards
Dolly
