### ISSUE TITLE
Send Mail without Mailgun?

### ISSUE THREAD

**Issue by uggyk** [aqilix/zf3-apigilty-oauth2#6]
Firstly, terima kasih banyak atas project ini yang saya cari carii berbulanbulan. I have zero experience in php, but I ultimately have a good understanding of how the system and the api works. I don't think I'll be asking this question if not from the above. 

but is Mailgun necessary in order to advance? I haven't cloned the project yet. I just read through the source code. 

I am hoping to use my Hosting providers smtp mailer instead of Mailgun. I know Mailgun is an impressive validator, but I believe my own webmail server could handle these events.

**Comment by dollyaswin** [comment]
Hi @uggyk,

Thanks for your question. Mailgun is not required for this project. I just use it to make sure the mail sender works. You can follow the SMTP configuration here

https://github.com/aqilix/zf3-apigilty-oauth2/blob/master/config/autoload/mailtransport.local.php.dist

Regards
Dolly

**Comment by uggyk** [comment]
sweet. thank you very much Mr. Dolly.
